### ISSUE TITLE
problem with the package (npm)

### ISSUE THREAD

**Issue by danielzzz** [pkrumins/node-base64#1]
node 0.1.103 (nvm) + npm

it seems npm generates an incorrect main.js file for node-base64 (this maybe because this module is compiled), the problem is in the line 5 (/lib/node/.npm/node-base64/0.0.1/main.js)

module.exports = require("./package/build/default/")

it should be:
module.exports = require("./package/build/default/base64")

I reported something similar to isaacs once and he thougth it's a problem in this file:

Bug in base64 package.json. It should read "main":"./build/default/base64"

thanks!
danielz

**Comment by pkrumins** [comment]
This is actually not my base64 module. There are like 10 of them.

This one is astro's (github.com/astro/node-base64).

Mine works 100% cause it creates a symlink right after compilation.

Also that one leaks memory after each decode and there are no binary tests. Afaik all of base64 modules are broken for binary data. That's why I wrote mine cause I needed binary encoding to work 100%.

**Comment by danielzzz** [comment]
ah, ok - sorry then. I will keep it in mind.

thanks!
danielz

**Comment by pkrumins** [comment]
use my module, it now has 21 binary test that passes.
